---
- name: Configure Frontend Web Servers
  hosts: frontend
  become: yes
  roles:
    - frontend

- name: Configure Database Servers
  hosts: database
  become: yes
  roles:
    - database

- name: Configure Backend Python Servers
  hosts: backend
  become: yes
  roles:
    - backend